"use strict";

exports.__esModule = true;

var _createThemedIcon = require("./utils/createThemedIcon");

var _IconSignalCellularConnectedNoInternet2BarFilled = require("./IconSignalCellularConnectedNoInternet2BarFilled");

var _IconSignalCellularConnectedNoInternet2BarOutlined = require("./IconSignalCellularConnectedNoInternet2BarOutlined");

var _IconSignalCellularConnectedNoInternet2BarRounded = require("./IconSignalCellularConnectedNoInternet2BarRounded");

var _IconSignalCellularConnectedNoInternet2BarSharp = require("./IconSignalCellularConnectedNoInternet2BarSharp");

var _IconSignalCellularConnectedNoInternet2BarTwoTone = require("./IconSignalCellularConnectedNoInternet2BarTwoTone");

var IconSignalCellularConnectedNoInternet2Bar =
/*#__PURE__*/
function IconSignalCellularConnectedNoInternet2Bar(props) {
  return (0, _createThemedIcon.createThemedIcon)(props, _IconSignalCellularConnectedNoInternet2BarFilled.IconSignalCellularConnectedNoInternet2BarFilled, _IconSignalCellularConnectedNoInternet2BarOutlined.IconSignalCellularConnectedNoInternet2BarOutlined, _IconSignalCellularConnectedNoInternet2BarRounded.IconSignalCellularConnectedNoInternet2BarRounded, _IconSignalCellularConnectedNoInternet2BarSharp.IconSignalCellularConnectedNoInternet2BarSharp, _IconSignalCellularConnectedNoInternet2BarTwoTone.IconSignalCellularConnectedNoInternet2BarTwoTone);
};

exports.IconSignalCellularConnectedNoInternet2Bar = IconSignalCellularConnectedNoInternet2Bar;