"use strict";

exports.__esModule = true;

var _IconSignalCellularConnectedNoInternet3BarOutlined = require("./IconSignalCellularConnectedNoInternet3BarOutlined");

exports.IconSignalCellularConnectedNoInternet3BarSharp = _IconSignalCellularConnectedNoInternet3BarOutlined.IconSignalCellularConnectedNoInternet3BarOutlined;