"use strict";

exports.__esModule = true;

var _createThemedIcon = require("./utils/createThemedIcon");

var _IconSignalCellularConnectedNoInternet4BarFilled = require("./IconSignalCellularConnectedNoInternet4BarFilled");

var _IconSignalCellularConnectedNoInternet4BarOutlined = require("./IconSignalCellularConnectedNoInternet4BarOutlined");

var _IconSignalCellularConnectedNoInternet4BarRounded = require("./IconSignalCellularConnectedNoInternet4BarRounded");

var _IconSignalCellularConnectedNoInternet4BarSharp = require("./IconSignalCellularConnectedNoInternet4BarSharp");

var _IconSignalCellularConnectedNoInternet4BarTwoTone = require("./IconSignalCellularConnectedNoInternet4BarTwoTone");

var IconSignalCellularConnectedNoInternet4Bar =
/*#__PURE__*/
function IconSignalCellularConnectedNoInternet4Bar(props) {
  return (0, _createThemedIcon.createThemedIcon)(props, _IconSignalCellularConnectedNoInternet4BarFilled.IconSignalCellularConnectedNoInternet4BarFilled, _IconSignalCellularConnectedNoInternet4BarOutlined.IconSignalCellularConnectedNoInternet4BarOutlined, _IconSignalCellularConnectedNoInternet4BarRounded.IconSignalCellularConnectedNoInternet4BarRounded, _IconSignalCellularConnectedNoInternet4BarSharp.IconSignalCellularConnectedNoInternet4BarSharp, _IconSignalCellularConnectedNoInternet4BarTwoTone.IconSignalCellularConnectedNoInternet4BarTwoTone);
};

exports.IconSignalCellularConnectedNoInternet4Bar = IconSignalCellularConnectedNoInternet4Bar;