import { FilledSignalCellularConnectedNoInternet2Bar as OutlineSignalCellularConnectedNoInternet2Bar } from './FilledSignalCellularConnectedNoInternet2Bar'
export { OutlineSignalCellularConnectedNoInternet2Bar }
