import { FilledSignalCellularConnectedNoInternet1Bar as SharpSignalCellularConnectedNoInternet1Bar } from './FilledSignalCellularConnectedNoInternet1Bar'
export { SharpSignalCellularConnectedNoInternet1Bar }
