import { FilledSignalCellularConnectedNoInternet4Bar as TwoToneSignalCellularConnectedNoInternet4Bar } from './FilledSignalCellularConnectedNoInternet4Bar'
export { TwoToneSignalCellularConnectedNoInternet4Bar }
